name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
          AMQP_URL: "amqp://guest:guest@rabbitmq:5672"
        ports:
          - 5672:5672
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Build
        run: |
          sudo apt install -y libsystemd-dev
          go build

      - name: Test
        run: |
          sudo apt install -y softhsm2 opensc
          sudo env "PATH=$PATH" go test -v $(go list ./... | grep -v "/vendor\|downloader\|alerts") -failfast -coverprofile=coverage.out -covermode=atomic
          sudo chmod 666 coverage.out

      - name: Code coverage
        run: bash <(curl -s https://codecov.io/bash)

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43.0
          skip-go-installation: true
